src/Cerebral.js
src/core/createSignalMethod.js

There were a couple of hidden characters in here causing me errors in Chrome.
I've removed them.

remove hidden characters

---

CHANGELOG.md

Hello,
I started a change log based on what I could understand from the commits. I think it would be helpful when migrating from one version to the next

Started changelog to track api changes

---

CHANGELOG.md

Hi Christian, here are the latest changes I could gather from the commits. Feel free to update as necessary.
Thanks,

Update changelog up to 0.18.4

---

demo/actions/setFilter.js
package.json

[todomvc demo](http://www.christianalfoni.com/todomvc/):
* published with latest router which isn't in deps yet
* `setFilter` action wasn't updated to latest router changes
@christianalfoni  say if I should also add updated `demo_dist` to this commit

update todomvc demo to latest cerebral-router

---

README.md

Just fixing up all the old links in the readme. Broken images and the like make the project look stale.

docs(readme): update website paths

---

src/index.js

feat(extend): provide registered signals to module's init method

---

src/CreateSignalFactory.js

Improve controller events

---

src/index.js

Controller keeps a reference to modules which can be used by cerebral-react so that we can pass modules to components.
Example module:
```js
// /app/modules/home/index.js
import Component from './components';
export default {
init() {
return {
Component
};
},
signals: {
opened: []
},
services: {}
};
```
Loading modules:
```js
// /app/main.js
// load the modules
import pouchdb from 'cerebral-pouchdb';
import home from './modules/home';
import notFound from './modules/notFound';
const modules = {
db: pouchdb({
localDb: 'mydb',
remoteDb: 'http://localhost:3000/db/mydb'
}),
home,
notFound
};
// init the modules
import controller from './controller';
controller.extends(modules);
// init the router
import Router from 'cerebral-router';
Router(controller, {
'/': 'home.opened',
'*': …
```

controller.extends now supports signals, services and other meta

---

src/Devtools.js

Changed Event to CustomEvent for IE compatibility

---

src/CreateSignalFactory.js
tests/signals.js
tests/store.js

resolves #176 
@christianalfoni review process:
```sh
git checkout issue-176
git checkout HEAD~1 # switch to commit with failing tests
npm test # examine failing test
git checkout issue-176 # switch to fix
npm test # examine successful test
```
* say if it looks good for you in comment
* avoid using green `Merge pull-request` button
* I will push it to master

 emit signal and actions events in correct order

---

src/Compute.js
tests/computed.js

we can create a pr to make reviews

Computed factories

---

sr-prerelease.js
src/Compute.js
src/CreateSignalFactory.js
tests/computed.js

introduce `signalTrigger` event

---

src/modules/devtools/index.js
src/modules/recorder/index.js
src/modules/signalStore/index.js

fixing devtools

---

src/Compute.js

Factories inside factories where not added correctly

fix(Computed): run lazy factories correctly

---

src/CreateRegisterModules.js
src/CreateSignalFactory.js

Modules loaded

---

src/CreateSignalFactory.js
src/createActionArgs.js
src/staticTree.js
tests/signals.js
tests/staticTree.js
tests/store.js

tracking service usage will allow debugger to display the information

feat(debugger): wrap services to track usage

---

src/CreateSignalFactory.js
src/createActionArgs.js
tests/signals.js

wrapped services also needs to wrap prototype methods

fix(signalStore): wrap prototyped methods

---

src/index.js
tests/signals.js

fix: keep local signal options from interfering with global options

---

src/index.js
tests/server.js

Fix ServerController get

---

src/Computed.js
tests/computed.js

There was a bug related to nested computed

fix(computed): make nested computed update as well

---

src/Computed.js

to experiment with the new strict render syntax we need computed to handle the glob pattern

feat(computed): allow * and ** selectors in computed path

---

src/Computed.js

Fixed this issue: https://github.com/cerebral/cerebral/issues/291

fix(computed): should update cache on parent path update

---

packages/function-tree/package.json
packages/function-tree/src/Abort.js
packages/function-tree/src/Path.js
packages/function-tree/src/executeTree.js
packages/function-tree/src/factories/debounce.js
packages/function-tree/src/index.js
packages/function-tree/src/providers/Context.js
packages/function-tree/src/providers/Debugger.js
packages/function-tree/src/providers/Execution.js
packages/function-tree/src/providers/Input.js
packages/function-tree/src/providers/NodeDebugger.js
packages/function-tree/src/providers/Path.js
packages/function-tree/src/providers/Redux.js
packages/function-tree/src/staticTree.js
packages/function-tree/tests/FunctionTree.js
packages/function-tree/tests/contextProvider.js
packages/function-tree/tests/executionProvider.js
packages/function-tree/tests/inputProvider.js
packages/function-tree/tests/nodeDebuggerProvider.js
packages/function-tree/tests/pathProvider.js

refactor(function-tree): refactor to ES6

---

packages/cerebral/src/operators/helpers/populatePath.js
packages/cerebral/src/operators/operators.test.js
packages/cerebral/src/operators/set.js

Path population would break on multiple values.

Operator path fix

---

packages/cerebral/src/providers/providers.test.js
packages/cerebral/src/react/react.test.js
packages/cerebral/src/viewFactories/Hoc.js

Added a test in react.test.js using Computed and HOC.

fix(Computed): use new Computed API in HOC

---

packages/function-tree/package.json

Remove unused dependencies and npm scripts.

chore(function-tree): cleanup package definition

---

packages/cerebral-forms/src/utils/util.test.js

test: added validate test

---

packages/cerebral-forms/package.json
packages/cerebral-module-useragent/package.json
packages/cerebral-provider-http/package.json
packages/cerebral-router/package.json
packages/cerebral-todomvc/package.json
packages/cerebral/package.json
packages/function-tree/package.json

Add missing urls, fix some urls and add peer dependency.

Chore: Fix urls and dependencies

---

packages/cerebral/src/Controller.js
packages/cerebral/src/devtools/index.js
packages/cerebral/src/providers/Recorder.js
packages/cerebral/src/viewFactories/Hoc.js

The debugger (which is already released) will now update as the playback runs. Also prepared to do more awesome stuff here like implement a recorder into the debugger, but that is for later.

feat(Providers): update debugger on recorder playback

---

packages/function-tree/README.md

feat(function-tree): trigger pathStart and pathEnd events

---

README.md
package.json

resolves #329 
First iteration, please review :)

docs(All): add contribution docs

---

packages/cerebral/src/Controller.js
packages/cerebral/src/devtools/index.js
packages/cerebral/src/react/react.test.js

The correct devtools option was not used

fix(Devtools): use correct verifyStrictRender option

---

packages/cerebral-forms/README.md

Update README for forms

---

packages/cerebral/src/Controller.js
packages/cerebral/src/devtools/index.js
packages/cerebral/src/providers/Debugger.js
packages/docs/content/getting-real/03_devtools.en.md
packages/function-tree/src/FunctionTree.test.js
packages/function-tree/src/executeTree.js
packages/function-tree/src/index.js

As @schotime suggested, add a prop to throw error when overriding input props

feat(Devtools): add option to throw error when overwriting input prop

---

packages/cerebral-provider-http/src/index.js

i'm using ms web api. if a result from post is empty there is no content-type from server

http provider post empty result

---

packages/docs/content/api/08_router.en.md
packages/docs/content/get-started/01_get-started.en.md
packages/docs/content/getting-real/07_routing.en.md
packages/docs/themes/cerebral-website/footer/footer.bemhtml.js

Updated install for cereral and router, added contributors link to Cerebral repo (another magical thing with monorepo :D )

docs(website): add install and contributors

---

package.json
packages/docs/content/tutorial/01_introduction.en.md
packages/docs/content/tutorial/02_define-state.en.md
packages/docs/content/tutorial/03_render-state.en.md
packages/docs/content/tutorial/04_update-state.en.md
packages/docs/content/tutorial/05_using-chains.en.md
packages/docs/content/tutorial/06_using-inputoutput.en.md
packages/docs/content/tutorial/07_using-async-actions.en.md
packages/docs/content/tutorial/08_using-paths.en.md
packages/docs/content/tutorial/09_compute_state.en.md
packages/docs/content/tutorial/10_providers.en.md
packages/docs/content/tutorial/11_routing.en.md
packages/docs/content/tutorial/12_refactoring_modules.en.md
packages/tutorial/package.json
packages/tutorial/scripts/run.js

Added inquirer to load chapters, also updated docs

Tutorial feedback1

---

packages/docs/content/tutorial/06_using-inputoutput.en.md

wrong path to file

---

packages/cerebral-provider-http/README.md
packages/cerebral-provider-http/package.json
packages/cerebral-provider-http/src/DEFAULT_OPTIONS.js
packages/cerebral-provider-http/src/factories/httpDelete.js
packages/cerebral-provider-http/src/factories/httpGet.js
packages/cerebral-provider-http/src/factories/httpPatch.js
packages/cerebral-provider-http/src/factories/httpPost.js
packages/cerebral-provider-http/src/factories/httpPut.js
packages/cerebral-provider-http/src/http.test.js
packages/cerebral-provider-http/src/index.js
packages/cerebral-provider-http/src/request.js
packages/cerebral-provider-http/src/utils.js

feat(http): refactored, documented and added factories

---

packages/cerebral-forms/src/factories/validateForm.js
packages/cerebral-forms/src/helpers/isValidForm.test.js

Also added failing test for validateForm

fix: errorMessages throws error when empty

---

packages/cerebral-provider-firebase/README.md
packages/cerebral-provider-firebase/src/factories/createUserWithEmailAndPassword.js
packages/cerebral-provider-firebase/src/factories/getUser.js
packages/cerebral-provider-firebase/src/factories/off.js
packages/cerebral-provider-firebase/src/factories/onChildAdded.js
packages/cerebral-provider-firebase/src/factories/onChildChanged.js
packages/cerebral-provider-firebase/src/factories/onChildRemoved.js
packages/cerebral-provider-firebase/src/factories/onValue.js
packages/cerebral-provider-firebase/src/factories/push.js
packages/cerebral-provider-firebase/src/factories/remove.js
packages/cerebral-provider-firebase/src/factories/sendPasswordResetEmail.js
packages/cerebral-provider-firebase/src/factories/set.js
packages/cerebral-provider-firebase/src/factories/signInAnonymously.js
packages/cerebral-provider-firebase/src/factories/signInWithEmailAndPassword.js
packages/cerebral-provider-firebase/src/factories/signInWithFacebook.js
packages/cerebral-provider-firebase/src/factories/signOut.js
packages/cerebral-provider-firebase/src/factories/task.js
packages/cerebral-provider-firebase/src/factories/transaction.js
packages/cerebral-provider-firebase/src/factories/update.js
packages/cerebral-provider-firebase/src/factories/utils.js
packages/cerebral-provider-firebase/src/factories/value.js
packages/cerebral-provider-firebase/src/index.js
packages/cerebral-provider-firebase/src/set.js
packages/cerebral-provider-firebase/src/transaction.js
packages/cerebral-provider-firebase/src/update.js

Added a bunch of factories supporting template tags... also documentation. This is becoming a really powerful thing now :)

feat(firebase): add factories

---

packages/cerebral-forms/.npmignore
packages/cerebral-module-useragent/.npmignore
packages/cerebral-provider-firebase/.npmignore
packages/cerebral-provider-http/.npmignore
packages/cerebral-router/.npmignore
packages/cerebral/.npmignore
packages/function-tree/.npmignore

chore: add babel config and sources to npmignore

---

README.md
packages/cerebral-forms/README.md
packages/cerebral-module-useragent/README.md
packages/cerebral-provider-firebase/README.md
packages/cerebral-provider-http/README.md
packages/cerebral/README.md
packages/function-tree/README.md

Instructions in monorepo README only, references to in individual packages

docs(all): add new install instructions and reference monorepo

---

packages/docs/content/migration/01_start_migration.en.md

docs(website): adding missing part to migration

---

packages/cerebral-debugger/package.json
packages/docs/content/get-started/02_debugger.en.md
packages/docs/content/getting-real/03_devtools.en.md

Okay, got them built and uploaded to Google Drive for now... completely open to put them somewhere else :) But at least now people can try it out!

docs(website): add standalone debugger downloads

---

packages/docs/themes/cerebral-website/heading/heading.css
packages/docs/themes/cerebral-website/menu-item/_theme/menu-item_theme_islands.css
packages/docs/themes/cerebral-website/page/page.css

Okay, I have made improvements to font size and menu selection. Looks less cluttered now :)

docs(website): fix font size and menu selection indication

---

packages/tutorial/scripts/prepare.js

chore(tutorial): fix chapter distribution to website

---

packages/docs/themes/cerebral-website/code/code.css
packages/docs/themes/cerebral-website/heading/heading.css
packages/docs/themes/cerebral-website/menu-item/_theme/menu-item_theme_islands.css

Just some minor styling improvements for readability.

docs(website): add spacing between paragraphs and support for h4

---

packages/cerebral/src/devtools/index.js
packages/todomvc/src/controller.js

Also made todomvc connect to default standalone debugger port. Cause it falls back to chrome extension anyways.
Also added a warning about it

fix(Devtools): fix sending initial backlog

---

packages/cerebral-forms/README.md

It seems the path to the form field is incorrect

Fix form field path in README

---

packages/docs/content/api/07_operators.en.md
packages/docs/themes/cerebral-website/code/code.css
packages/docs/themes/cerebral-website/heading/heading.css
packages/docs/themes/cerebral-website/page/__content/page__content.css

Limit paragraph and code blocks width, add support for inline `code`.

Improved operator documentation and website style

---

packages/cerebral-forms/src/rules.js
packages/cerebral-forms/src/rules.test.js

fix(forms): minLength do not fail when field is empty

---

packages/cerebral-provider-firebase/README.md
packages/cerebral-provider-firebase/src/delete.js
packages/cerebral-provider-firebase/src/factories/delete.js
packages/cerebral-provider-firebase/src/factories/put.js
packages/cerebral-provider-firebase/src/helpers.js
packages/cerebral-provider-firebase/src/index.js
packages/cerebral-provider-firebase/src/push.js
packages/cerebral-provider-firebase/src/put.js
packages/cerebral-provider-firebase/src/set.js
packages/cerebral-provider-firebase/src/update.js
packages/cerebral-provider-firebase/src/value.js
packages/docs/content/api/06_operators.en.md

this changes implementation of many firebase methods to fix the custom Promise use by firebase. Not all methods are fixed though.
See README for API.

Firebase upload

---

packages/demo/src/common/Collection/signals/remove.js
packages/demo/src/common/Collection/signals/update.js

A small change in firebase provider for upload was not reflected in the demo. This fixes it.

fix(demos): fix image upload

---

packages/function-tree-debugger/electron/package.json
packages/function-tree-debugger/package.json
packages/function-tree-debugger/src/components/Debugger/Signals/Signal/Action/Service/styles.css
packages/function-tree/src/devtools/index.js

This includes a couple of CSS fixes

feat(function-tree): give warning when not able to connect to debugger

---

packages/docs/themes/cerebral-website/code/code.css
packages/docs/themes/cerebral-website/prism/prism.css

style(website): use light theme for code blocks

---

packages/cerebral-provider-firebase/src/createUserWithEmailAndPassword.js
packages/cerebral-provider-firebase/src/getUser.js
packages/cerebral-provider-firebase/src/signInAnonymously.js
packages/cerebral-provider-firebase/src/signInWithEmailAndPassword.js
packages/cerebral-provider-firebase/src/signInWithFacebook.js
packages/cerebral-provider-firebase/src/signInWithGoogle.js
packages/cerebral-provider-firebase/src/transaction.js

@christianalfoni or anyone using firebase, could you do some testing with mock data to make sure this change (no tests!) does not break any production app ?

fix(firebase): fix code to not use buggy 'catch' from firebase promises

---

packages/cerebral/src/viewFactories/Hoc.js
packages/cerebral/src/viewFactories/react.test.js

fix(Views): fix dynamic signals not receiving passed props

---

packages/cerebral-module-useragent/src/index.js
packages/cerebral-module-useragent/src/signalFactories/offlineChanged.js
packages/cerebral-module-useragent/src/signalFactories/windowChanged.js

fix(useragent): module path is now string

---

debugger/cerebral-debugger/src/components/Debugger/Model/index.js
debugger/cerebral-debugger/src/components/Debugger/Signals/index.js
debugger/cerebral-debugger/src/components/Debugger/Toolbar/index.js
debugger/cerebral-debugger/src/components/Debugger/index.js
debugger/cerebral-debugger/src/components/Debugger/styles.css
debugger/cerebral-debugger/src/modules/Debugger/actions/parseAndRunMessages.js
debugger/cerebral-debugger/src/modules/Debugger/index.js

Also includes optimization and indication of catching up with app state

fix(debugger): fix responsive handling of debugger

---

docs/docs/docs/best_practices/testing.md

Added docs for runCompute, runAction and runSignal test helpers

docs(testing): Added docs for test helpers

---

docs/docs/docs/api/compute.md

removing a stale closing parenthesis

fix(website): typo in computed composing snippet

---

docs/docs/docs/api/compute.md

docs(website): fix arg usage in sample snippet

---

packages/function-tree/src/FunctionTree.test.js
packages/function-tree/src/executeTree.js

fix(function-tree): fix issue with functions after sequence

---

packages/function-tree/src/index.js
packages/function-tree/src/index.test.js

@christianalfoni please have a look and see if this is ok and doesn't break anything I may have missed.

feat(function-tree): abort tree execution from async action

---

debugger/connector/index.js
debugger/electron/devServer.js
debugger/electron/main.js
debugger/package.json
debugger/src/components/Debugger/index.js
packages/cerebral/src/devtools/index.js

When focusing app in Chrome debugger switches to that tab in debugger

feat(debugger): auto switch to app when focused

---

debugger/electron/devServer.js
debugger/src/components/Debugger/Inspector/index.js

Fixed issue where changing array value does not work

fix(debugger): fix array manual mutation

---

docs/docs/docs/developer_guide/actions.md
docs/docs/docs/developer_guide/compute.md
docs/docs/docs/developer_guide/connect.md
docs/docs/docs/developer_guide/factories.md
docs/docs/docs/developer_guide/index.md
docs/docs/docs/developer_guide/operators.md
docs/docs/docs/developer_guide/paths.md
docs/docs/docs/developer_guide/routing.md
docs/docs/docs/developer_guide/state.md
docs/docs/docs/get_started/debugger.md
docs/docs/docs/get_started/index.md
docs/docs/docs/get_started/resources.md
docs/docs/docs/get_started/the_architecture.md
docs/docs/docs/packages/firebase.md
docs/docs/docs/packages/function_tree.md
docs/docs/docs/packages/index.md

After next release I will make tutorial and webpackbins completely aligned :)

docs(website): iterate docs, general improvements and API alignment

---

packages/cerebral-provider-forms/src/operators/index.js

setField seems to to have been missed from the operator index.js

fix(forms): export setField with other operators

---

packages/cerebral-provider-forms/src/form.js
packages/cerebral-provider-forms/src/operators/isValidForm.js
packages/cerebral-provider-forms/src/operators/isValidForm.test.js
packages/cerebral-provider-forms/src/operators/resetForm.test.js
packages/cerebral-provider-forms/src/operators/setField.test.js

Also add check in form to ensure that the tag/compute resolves to an object
fixes #744

fix(forms): Allow isValidForm operator to work with any tag or compute

---

docs/packages/forms.md
packages/cerebral-provider-forms/src/form.js
packages/cerebral-provider-forms/src/form.test.js

feat(cerebral-provider-forms): expose all fields

---

packages/function-tree/src/Abort.js
packages/function-tree/src/index.js
packages/function-tree/src/index.test.js
packages/function-tree/src/providers/Execution.js

feat(function-tree): pass payload when aborting

---

debugger/src/components/Debugger/App/index.js
debugger/src/components/Debugger/App/styles.css
debugger/src/components/Debugger/Signals/List/index.js
debugger/src/components/Debugger/Signals/List/styles.css
debugger/src/components/Debugger/Signals/Signal/index.js
debugger/src/components/Debugger/Signals/Signal/styles.css
debugger/src/components/Debugger/Toolbar/index.js
debugger/src/components/Debugger/Toolbar/styles.css
debugger/src/modules/Debugger/actions/addSignal.js

style(debugger): fix idle position and indicate FT when in cft mode

---

debugger/src/components/Debugger/Signals/Signal/Action/Mutation/index.js
debugger/src/components/Debugger/Signals/Signal/Action/Service/index.js
debugger/src/components/Debugger/Signals/Signal/Action/index.js
debugger/src/components/Debugger/Signals/Signal/Action/styles.css
debugger/src/components/Debugger/Signals/Signal/index.js
debugger/src/components/Debugger/Signals/Signal/styles.css

style(debugger): iterate style of debugger

---

packages/function-tree/README.md
packages/function-tree/providers.js
website/builder/package.json

chore: Fix some problems when running setup

---

packages/cerebral-provider-forms/src/index.js
packages/cerebral-provider-forms/src/index.test.js

docs suggests toJSON in provider

toJSON added to provider

---

debugger/src/components/Debugger/Signals/Signal/Action/styles.css
docs/api/index.md
packages/cerebral/src/Controller.js
packages/function-tree/src/index.js

- Updated docs
- fixed a tiny style bug on error in debugger

fix(function-tree): throw error after emitting error in ft

---

.travis.yml
codemods/.editorconfig
codemods/.gitignore
codemods/1.x-2.x/README.md
codemods/1.x-2.x/__testfixtures__/computed-decorator.input.js
codemods/1.x-2.x/__testfixtures__/computed-decorator.output.js
codemods/1.x-2.x/__testfixtures__/computed.input.js
codemods/1.x-2.x/__testfixtures__/computed.output.js
codemods/1.x-2.x/__testfixtures__/controller.input.js
codemods/1.x-2.x/__testfixtures__/controller.output.js
codemods/1.x-2.x/__testfixtures__/operators-flow.input.js
codemods/1.x-2.x/__testfixtures__/operators-flow.output.js
codemods/1.x-2.x/__testfixtures__/operators-state.input.js
codemods/1.x-2.x/__testfixtures__/operators-state.output.js
codemods/1.x-2.x/__tests__/computed-test.js
codemods/1.x-2.x/__tests__/controller-test.js
codemods/1.x-2.x/__tests__/operators-test.js
codemods/1.x-2.x/computed.js
codemods/1.x-2.x/controller.js
codemods/1.x-2.x/operators.js
codemods/1.x-2.x/package.json
lerna.json

Addresses https://github.com/cerebral/cerebral/issues/318

[wip] Add codemods for moving from Cerebral 1.x to 2.x

---

website/builder/css/docs.css
website/builder/pages/docs/navigationMobile.js

The notable changes are the improvements to the hamburger menu icon, which should look nicer and work better, and the removal of dead CSS. The remaining changes are minor layout fixes.

fix(website): clean unused CSS and improve the UX

---

codemods/1.x-2.x/README.md
codemods/1.x-2.x/controller.js
codemods/1.x-2.x/operators.js

I tested the codemods on my cerebral 1 codebase and came up with some minor issues. I've also added a basic readme on usage.

Fix errors with codemods and add a basic usage readme

---

packages/cerebral/src/devtools/index.js

After ImageData addition the devtools didn't work with jest.

chore: allow devtools to work with jest

---

docs/api/connect.md
docs/developer_guide/compute.md
docs/developer_guide/providers.md
docs/developer_guide/routing.md
website/builder/builder/extractMarkdownFiles.js
website/builder/pages/docs/doc.js
website/builder/pages/docs/index.js

- http error and router tutorial docs updated to latest version (also webpackbin is updated)
- fixed editing docs github links
- Improved provider docs
- Added mergeProps docs

Website fixes

---

debugger/src/components/Debugger/Mutations/index.js
debugger/src/components/Debugger/Mutations/styles.css
debugger/src/components/Debugger/Signals/Signal/index.js
debugger/src/components/Debugger/Signals/Signal/styles.css
debugger/src/components/Debugger/index.js
debugger/src/components/Debugger/styles.css
debugger/src/modules/Debugger/signals/signalClicked.js

- Normal font size on inactive path names
- You can now click a signal in mutations list and it opens signals tab with that signal highlighted
- Any uncaught errors is now shown and you can click a button to restart debugger

feat(debugger): make general improvements to debugger

---

docs/get_started/get_started.md
website/builder/builder/extractMarkdownFiles.js
website/builder/package.json

Maaaan, this was so awesome. Took me seconds to make youtube embed available in our Markdown code :-)

feat(website): add marksy and youtube component

---

packages/cerebral/src/Controller.js

corrected documentation url for debugger

---

website/builder/config.json

Just proposing a top menu change, aiming for a better mental flow, such as:
"get started" -> How can I have a quick look into this new stuff?
"developer guide" -> Ok, seems cool, let me have a closer look, how this all works.
"api" -> I want to use it.
"packages" -> What else can I get?
"migration" -> The old dogs already know about Cerebral, but great they find information, how to migrate it, finally!

Update config.json for a better user experience

---

packages/cerebral-provider-firebase/README.md
packages/cerebral-provider-firebase/src/helpers.js
packages/cerebral-provider-firebase/src/operators/off.js

Changed API of `off` to be more powerful

Firebase listener fix

---

packages/cerebral/src/test/index.js
packages/cerebral/src/test/index.test.js

fix(testing): runSignal now supports function-tree primitives

---

packages/cerebral/src/Module.js
packages/cerebral/src/Module.test.js

fixes https://github.com/cerebral/cerebral/issues/852

Better error message on undefined signal

---

packages/cerebral/src/tags/index.js
packages/cerebral/src/tags/index.test.js

Validate interpolated values inside of tags and throw with meaningful error

---

packages/cerebral/src/Model.js
packages/cerebral/src/providers/State.test.js

fix(Model): fix setting paths with an array index

---

packages/cerebral/package.json
packages/cerebral/src/operators/when.js
packages/cerebral/src/operators/when.test.js

fix(Operators): operator when: throw errors for wrong input

---

packages/function-tree-firebase-admin/.babelrc
packages/function-tree-firebase-admin/README.md
packages/function-tree-firebase-admin/src/Provider.js
packages/function-tree-firebase-admin/src/QueueHandler.js
packages/function-tree-firebase-admin/src/createTask.js
packages/function-tree-firebase-admin/src/errors.js

*) Updated some docs
*) Allow to specify authentication true or false
*) add task to provider

function-tree-firebase-admin specify authentication, task

---

packages/cerebral/package.json
packages/cerebral/src/Controller.js
packages/cerebral/src/Controller.test.js

fix(Controller): catch error chain for signal ran with Controller.runSignal

---

packages/forms/src/utils/validate.js
packages/forms/src/utils/validate.test.js

refactor(forms): remove failedRule from initialValidation

---

docs/api/operators.md
packages/cerebral/src/operators/increment.js
packages/cerebral/src/operators/increment.test.js
packages/cerebral/src/operators/index.js

I thought that a generic increment operator might be a handy addition. :)

feat(operator): Add increment operator.

---

docs/introduction/connect.md

docs(tutorial): added a link from the guide to API about connect

---

package.json
packages/cerebral/package.json
packages/firebase/package.json
packages/forms/package.json
packages/function-tree/package.json
packages/http/package.json
packages/router/package.json
packages/shortcuts/package.json

This fixes bug when running tests in current master. The commit is by @reflog and was on Typescript branch. Moving it here to ease things.

chore: corrected package.json to make sure tests can run on windows

---

docs/introduction/what_is_cerebral.md
website/builder/css/main.css
website/builder/package.json

Fixes issue with markdown compiler, also supporting special marksy syntax on github

fix(website): update marksy version

---

docs/api/state.md
packages/cerebral/src/Model.js
packages/cerebral/src/Model.test.js
packages/cerebral/src/operators/toggle.js
packages/cerebral/src/providers/State.js
packages/cerebral/src/providers/State.test.js

Adds toggle mutation to state for convenience.

feat(state): add toggle mutation

---

packages/node_modules/cerebral/src/Controller.js

related https://github.com/cerebral/cerebral/pull/879

refactor(controller): change public getModule method to private function

---

packages/website/builder/builder/extractMarkdownFiles.js
packages/website/builder/package.json

This fixes issue with anchor links

chore(website): update marksy version

---

packages/node_modules/cerebral/src/utils.js

fix(Views): fix warning prop on state passed as prop

---

package.json
scripts/check.dependencies.js

If there are no conflicts, this automatically writes new dependencies in package.json.

feat(tooling): automatically write new dependencies in package.json

---

packages/node_modules/function-tree/src/staticTree.js
packages/node_modules/function-tree/src/staticTree.test.js

…and syntax when extracting their names.

fix(function-tree): fix name extraction for functions.

---

docs/api/components.md
packages/node_modules/cerebral/src/views/angularjs/connect.js
packages/node_modules/cerebral/src/views/angularjs/module.js

Add possibility for adding component name when using angular

feat(Views): Component name for Angular

---

packages/node_modules/cerebral/src/providers/State.test.js

Change test to support Node.js 8.

fix(State): support new error-wording of Node.js 8

---

packages/node_modules/cerebral/src/views/vue/connect.js

Just fixes issue where `$props` might be `undefined`

fix(Views): fix props bug with vue

---

packages/node_modules/@cerebral/router/README.md
packages/node_modules/@cerebral/router/src/base.js
packages/node_modules/@cerebral/router/src/index.js
packages/node_modules/@cerebral/router/src/router.js
packages/node_modules/@cerebral/router/src/router.test.js

Added back getSignalUrl. In combination with the new `UniversalController` and loading the router on server side, this should "just work" :-)

feat(router): add getSignalUrl back

---

packages/node_modules/@cerebral/firebase-admin/.npmignore
packages/node_modules/@cerebral/firebase/.npmignore
packages/node_modules/@cerebral/forms/.npmignore
packages/node_modules/@cerebral/http/.npmignore
packages/node_modules/@cerebral/router/.npmignore
packages/node_modules/@cerebral/shortcuts/.npmignore
packages/node_modules/@cerebral/storage/.npmignore
packages/node_modules/@cerebral/useragent/.npmignore
packages/node_modules/cerebral/.npmignore
packages/node_modules/function-tree/.npmignore

fix: only ignore top level `test` in .npmignore, fixes #1017

---

packages/website/builder/builder/extractMarkdownFiles.js
packages/website/builder/css/index.css
packages/website/builder/pages/index/index.js

- Pointing "Edit github" to next branch (not sure how we should ideally do this as this could cause a conflict with something already changed in next, but still... do not have to change target and rebase all over)
- Added youtube introduction
- Added copyright
- Fixed frontpage styling issue

Release website update

---

packages/node_modules/@cerebral/useragent/package.json

use next as deps version for Cerebral. Repo-cooker rewrites this on publish so it's not so bad but it needs to be fixed.

chore(useragent): fix package.json file  (tiny fix)

---

package.json
packages/website/builder/package.json
packages/website/publisher/package.json
scripts/packagesGlob.js
scripts/release/index.js

Makes master branch also run the website publishing script

chore(release): add website deploy to master script

---

packages/node_modules/@cerebral/firebase/README.md
packages/node_modules/@cerebral/firebase/index.d.ts
packages/node_modules/@cerebral/firebase/test/typescript/provider.test.ts

also added some missing types and docs

fix(firebase): fix an error in types not exporting provider as default

---

.eslintrc.json
packages/demos/demo/src/components/Header/index.js
packages/demos/demo/src/components/Today/index.js

PR is now ready. I removed the travis hack.

chore(deploy): fix website publishing

---

packages/node_modules/@cerebral/firebase/src/helpers.js
packages/node_modules/@cerebral/firebase/src/onDisconnect.js
packages/node_modules/cerebral/index.d.ts
packages/node_modules/cerebral/test/typescript/actions.ts

**firebase**
- Fixed a bug in firebase preventing proper error reporting.
- Fixed `off` method when it is not used with wildcard.
**cerebral**
- Fixed `resolve` type in cerebral (was missing optional overrideProps).

Fixes firebase & some types

---

packages/node_modules/cerebral/index.d.ts
packages/node_modules/cerebral/test/typescript/controller.ts
packages/node_modules/cerebral/test/typescript/signals.ts

Hello! Here is the little fixes for the typescript definitions.
This PR is update of #1117 with renamed branch.

fix(typescript): fix definitions for provide and controller catch option

---

packages/website/builder/css/index.css
packages/website/builder/css/main.css

fix mobile friendly frontpage and videos

---

docs/api/controller.md
docs/introduction/modules.md
packages/node_modules/@cerebral/storage/.babelrc
packages/node_modules/@cerebral/storage/README.md
packages/node_modules/@cerebral/storage/package.json
packages/node_modules/@cerebral/storage/src/StorageProvider.js
packages/node_modules/@cerebral/storage/src/StorageProviderError.js
packages/node_modules/@cerebral/storage/src/index.js
packages/node_modules/@cerebral/storage/src/index.test.js
packages/node_modules/@cerebral/storage/src/operators/getStorage.js
packages/node_modules/@cerebral/storage/src/operators/removeStorage.js
packages/node_modules/@cerebral/storage/src/operators/setStorage.js
packages/node_modules/cerebral/src/BaseController.js

BREAKING CHANGE:
remove does no longer return anything

add async storage handling

---

packages/website/builder/css/main.css
packages/website/builder/css/nav.css
packages/website/builder/pages/docs/doc.js
packages/website/builder/pages/docs/nav.js
packages/website/builder/scripts/hashToggleLinks.js

In order fix various small visual niggles in the menu it was necessary to refactor the menu css
significantly and the js code somewhat as well.

refactor(website): simplify and improve clarity of menu code

---

packages/node_modules/cerebral/src/utils.js

Fixes issue with sub modules in mobx-state-tree

fix(Controller): fix sub module extraction logic

---

docs/introduction/test.md
packages/node_modules/cerebral/index.d.ts
packages/node_modules/cerebral/src/test/index.js
packages/node_modules/cerebral/test.d.ts

https://github.com/cerebral/cerebral/pull/1158

feat(cerebral): expose the controller in CerebralTest response

---

docs/api/devtools.md
docs/introduction/debugger.md
packages/node_modules/cerebral/src/devtools/index.js
packages/node_modules/function-tree/README.md
packages/node_modules/function-tree/src/devtools/base.js
packages/node_modules/function-tree/src/devtools/index.js

Debugger is released with instructions on how to add an app with ssl support :)
https://github.com/cerebral/cerebral-debugger/pull/34

feat(Controller): add devtools ssl support

---

packages/node_modules/cerebral/index.d.ts

Added the generic for make definable type of signal, returning from ControllerClass.getSignal

ts: props type generic for Controller.getSignal

---

packages/node_modules/@cerebral/angular/src/ControllerService.ts
packages/node_modules/@cerebral/angular/test/angular.test.ts
packages/node_modules/cerebral/__test__/typescript/controller.ts
packages/node_modules/cerebral/__test__/typescript/modules.ts
packages/node_modules/cerebral/index.d.ts

This allows passing tests for angular. There are some open questions regarding "Provider" usage in function-tree and "add/removeModule" in controller.

ts(Module): update types with new module API

---

packages/node_modules/@cerebral/storage/index.d.ts

ts(storage): fix types with new Module

---

packages/node_modules/@cerebral/http/src/utils.js

fix(http): fix logic bug that caused onProgress event to always emit 0 or 1

---

docs/api/compute.md

compute -> Compute typo

---

docs/guides/http.md

in version 4 providers is now an object. Fixes #1266

Fix outdated doc for providers

---

README.md

Makes all badges the same style and from same source (img.shields.io).

 Changes all badges to use shields.io flat style

---

packages/website/builder/css/docs.css
packages/website/builder/css/nav.css
packages/website/builder/css/search.css

this commit and pull request:
- spaces out nav buttons a bit more
- removes some unused css
- ensures headers are visible when jumped to

fix(website): tweak css to improve the ux

---

docs/migration/5_0.md

docs(website) Update 5_0.md

---

packages/node_modules/@cerebral/inferno/README.md

Assigning App function to the controller it's wrong.

Wrong constant name

---

packages/node_modules/function-tree/src/providers/index.js

chore(function-tree): remove dead imports

---

docs/resources/utilities.md
packages/website/builder/config.json

Page to list and track useful packages to add to Cerebral proyects

docs(website): add utilities page
