- README.md
I didn't catch that async actions should not mutate state. Added a warning in the README in case others are confused as well.
> Add note about state parameter being read-only in async actions.

- src/analyze.js
Avoid the dreaded error: `Uncaught TypeError: Cannot read property 'output' of undefined` that can lead you down a huge timewasting spiral :)
We now get `Uncaught Error: Cerebral: Action number "0" in signal "keyPressed_left" does not exist. Check that you have spelled it correctly!`
> Update analyze.js to check to undefined action

- src/index.js
1. Adds support for modules without signals.
2. Adds support for registering sync signals. A module should be able to require that a signal is sync (same justification behind `controller.signalSync()`.
Modules now look like:
```js
export default {
init({controller, name, signals}) {
return ...
},
signals: {},
syncSignals: {},
services: {}
}
```
Not sure I'm sold on `syncSignals`. Maybe `signalsSync` to stay consistent with `signalSync()`?
> Feature(modules): make signals optional and support sync signals

- codecov.yml
Right now we just say "passed" at any percentage of coverage, but we can change this to "auto" to make sure coverage increases or stays the same to accept the commit
> Add coverage reports on pull requests

- README.md
- src/Computed.js
- tests/computed.js
We actually got into a situation where two computeds has the exact same state dependencies, but just runs them differently. So we need to put the actual function string representation into the computed cache key as well :)
> fix(computed): make callback part of cache key

- providers/stateProvider.js
- src/Computed.js
Due to computed now being "view driven", meaning it updates on "flush event" it needs to force recomputing its value when used in actions using: `state.computed`. The bottleneck of computed is not in signal, it is in rendering, so this is perfectly okay :)
> fix(computed): force computed to return value in actions

- src/staticTree.js
- tests/signals.js
- tests/staticTree.js
I think the best approach is to warn about actions running async which has not explicitly been set to running async. This way we handle the case where actions run async without you knowing about it. Which is the most important thing. The timeout is more of a feature which we could implement later if necessary.
> feat(asyncActions): warn about async actions

- providers/inputProvider.js
It has been quite common to pass in events and other bad data to signals. Typically events, because an inline use of signals on `onClick` etc passes in the event object. This code gives a warning during development when that happens :)
> fix(signalPayload): show warning when passing invalid payload to singal

- src/Computed.js
- tests/computed.js
Fixes issue where not passing in props to computed gives "undefined" as the props. Should be empty object.
> fix(computed): by default send object as props to computed

- src/index.js
It is just nicer to explain immediate with a factory than "hardcoding it".
```js
module.addSignals({
inputChanged: immediate(changeInput)
})
```
> feat(signals): expose immediate factory to create immediate signals

- src/Computed.js
The check in computed factory should happen before resolving paths or depsMap.
> perf(computed): check cached value as soon as possible.

- packages/cerebral/src/Controller.js
- packages/cerebral/src/Model.js
When `NODE_ENV==='production'` I got errors because devtools is null:
```js
const controller = Controller({
devtools: process.env.NODE_ENV === 'production' ? null : Devtools(),
...
```
With this change now this will not generate errors because `Model`'s constructor checks if `devtools` is `null` and do not try to get `preventExternalMutations` and `enforceSerializable` from a `null` parameter.
> Fix devtools null errors when in production

- packages/cerebral/src/DependencyStore.js
- packages/cerebral/tests/DependencyStore.js
When using deep paths such as 'foo.bar.baz', the resolution breaks after second depth level.
Added a test and a fix.
> fix(DependencyStore): fix deep path resolution

- packages/cerebral/src/Controller.js
- packages/cerebral/src/DependencyStore.js
- packages/cerebral/src/viewFactories/Container.js
- packages/cerebral/tests/DependencyStore.js
- packages/cerebral/tests/computed.js
- Added new option:
```js
Controller({
strictRender: true // False by default
})
```
- Dependency store now has two ways to extract components/computed to render/cachebust based on the change map
> feat(DependencyStore): introduce strict render as option

- packages/cerebral-router/src/index.js
- packages/cerebral-router/src/utils.js
- packages/cerebral-router/tests/matching.js
- packages/cerebral-router/tests/router.js
- packages/cerebral/src/Controller.js
- packages/cerebral/src/Module.js
I have added the routes config as an option to the router itself. I have kept the "routes by modules" to allow some more testing. Let us conclude after some discussion on it :)
> feat(cerebral-router): add routes config as option to router

- packages/cerebral/.babelrc
- packages/cerebral/tests/react.js
restored view tests but it fails now.
I think it is because of new strictRender.
@christianalfoni please push fix with another commit to this branch
> test(Views): restore accidently deleted tests

- packages/function-tree/src/index.js
> perf(function-tree): improve code readability and performance

- packages/cerebral/src/operators/debounce.js
- packages/cerebral/src/providers/index.js
- packages/function-tree-demos/src/mobx/run.js
- packages/function-tree-demos/src/node/runTask.js
- packages/function-tree-demos/src/redux/run.js
- packages/function-tree-firebase-demo/src/runTask.js
- packages/function-tree/README.md
- packages/function-tree/factories.js
- packages/function-tree/providers.js
- packages/function-tree/src/providers/Path.js
New syntax: import {ContextProvider} from 'function-tree/providers'
ISSUES CLOSED: #348 
Not sure how to test the function-tree-demos... Any hint ?
> chore(function-tree): add direct entry points to function-tree

- packages/cerebral/src/Computed.js
- packages/cerebral/src/Computed.test.js
- packages/cerebral/src/Model.js
- packages/cerebral/src/Model.test.js
- packages/cerebral/src/providers/State.js
- packages/cerebral/src/providers/providers.test.js
BREAKING CHANGE:
computed.getValue now takes model as argument instead of controller
ISSUES CLOSED: #354
API is `state.compute(computed, forceRecompute = false)` (using a verb like 'get', 'set', 'concat', etc).
> feat(Providers): get computed value with state.compute(computed)

- packages/function-tree/src/FunctionTree.test.js
- packages/function-tree/src/index.js
Pass the resulting payload to the end event - before the initial payload was passed instead.
> fix(function-tree): pass final resulting payload to end event

- packages/function-tree/README.md
Update code samples to invoke FunctionTree as a function not a constructor.
> docs(function-tree): remove new operator from code samples

- packages/cerebral-demo/src/components/UpperTitle/index.js
- packages/cerebral-todomvc/src/components/App/index.js
- packages/cerebral-todomvc/src/components/Footer/index.js
- packages/cerebral-todomvc/src/components/List/index.js
- packages/cerebral-todomvc/src/computed/isAllChecked.js
- packages/cerebral-todomvc/src/modules/app/actions/toggleAllChecked.js
- packages/cerebral/README.md
- packages/cerebral/src/Computed.js
- packages/cerebral/src/Computed.test.js
- packages/cerebral/src/Model.test.js
- packages/cerebral/src/providers/providers.test.js
- packages/cerebral/src/react/react.test.js
```js
connect({
foo: someComputed,
foo2: someComputed.props({foo: 'bar'})
})
```
```js
function someAction({state}) {
state.compute(someComputed)
state.compute(someComputed.props({foo: 'bar'})
}
```
BREAKING CHANGE:
Use "myComputed" instead of "myComputed()"
> feat(Computed): simplify use of computed without props

- README.md
The links were a little confusing in the README. The link text points to cerebral v1 docs, but clicking on the link takes you to cerebral v2 documentation.
> docs: disambiguate cerebral v1 and v2 in README

- packages/function-tree/src/FunctionTree.test.js
- packages/function-tree/src/staticTree.js
It should be possible to identify if the first function is running, this is used by the devtools. When the same function is used multiple times it risks getting index 0, which breaks devtools. This fix makes every function index unique, even though it is the same function.
> fix(function-tree): should give unique index for every function in tree

- packages/cerebral/src/Model.js
- packages/cerebral/src/Model.test.js
```js
model.unset(['foo', 'bar'])
```
Should notify changes like
```js
{foo: {bar: true}}
```
not
```js
{foo: true}
```
> fix(Model): fix unset to flush the path changes up to the removed key

- packages/cerebral/src/inferno/connect.js
- packages/cerebral/src/react/connect.js
- packages/cerebral/src/react/react.test.js
- packages/cerebral/src/viewFactories/Hoc.js
Added new signature:
```js
connect({/*paths*/}, {/*signals*/}, {/*props*/}, () => {})
```
Allows you to add arbitrary props passed into component.
> feat(Views): add ability to inject props to component

- packages/cerebral/src/Controller.js
- packages/cerebral/src/Model.js
- packages/cerebral/src/devtools/index.js
- packages/cerebral/src/react/react.test.js
- packages/cerebral/src/utils.js
- packages/cerebral/src/viewFactories/Container.js
After quite a few discussions I have implemented an error when using strict mode and replacing paths, causing components/computed not to update.
It happens when:
```js
{
foo: {
bar: 'baz'
}
}
```
You depend on path `foo.bar` and you do a `state.set('foo', {bar: 'baz2', wip: 'wop'})`. Whatever depends on `foo.bar` will not update because there was no change to that path. Now this throws an error encouraging you to depend on path `foo` instead, as it can be replaced.
Strict mode should not render children automatically because that is exactly what strict mode should not, it will break its most important optimization. We also investigated API extension like `foo.<.bar`... but this is taking it too far. It is better to adjust to strict modes special requirements to keep optimized UI. In our …
> feat(Devtools): throw error in strict mode when replacing paths

- packages/cerebral-todomvc/src/controller.js
- packages/cerebral/src/Computed.test.js
- packages/cerebral/src/Controller.js
- packages/cerebral/src/devtools/index.js
- packages/cerebral/src/operators/merge.js
- packages/cerebral/src/react/react.test.js
- packages/cerebral/src/utils.js
- packages/cerebral/src/viewFactories/Container.js
- components dependency store now in controller (allows multiple Container)
- Debugger logic for components moved into devtools
- Only verifyStrict on components as computeds are attached to components, no need for double check
- Fixed issue with merge, missing functionality (allowing template tags on merged prop values)
- Added `options` to controller for `strictRender`, more options coming
fixes #391
> feat(Devtools): dependencyStore usage refactored

- packages/cerebral/src/react/react.test.js
- packages/cerebral/src/viewFactories/Container.js
- packages/cerebral/src/viewFactories/Hoc.js
After discussions with @schotime we decided to just add an option for exposing the `signals` prop. Going all in with a generic extension API is just too much now. We can refactor this later if we decide to do something like that. But for now it is enough with this option.
> feat(Views): give option to expose the signals prop from c1

- packages/cerebral/src/operators/index.js
- packages/cerebral/src/operators/state.test.js
- packages/cerebral/src/operators/string.js
- packages/cerebral/src/operators/string.test.js
We need a tag template which just becomes a string. This will probably be the most useful tag template for app specific factories:
```js
showToast(string`Wow, awesome, ${state`user.name`}`)
```
Now you only need to check if argument is function and call it with `.toValue()` behind to extract and of these templates.
I am open to change the name, though `string` is generic and explicit.
> feat(Operators): add string template tag

- packages/cerebral/src/operators/helpers/populatePath.js
- packages/cerebral/src/operators/string.test.js
Now we can use computed in template literals:
```js
showSomething(string`You got ${totalUserScore} points!`)
```
> feat(Operators): allow operator template literals to use computed

- packages/cerebral/src/Controller.js
Avoid throwing warnings during testing. Using Cerebral with React Native or desktop apps is highly likely a path via testing it in the browser.
> feat(Devtools): only promote debugger when in browser

- packages/cerebral/src/Controller.js
- packages/cerebral/src/Controller.test.js
- packages/cerebral/src/operators/equals.test.js
- packages/cerebral/src/operators/unset.test.js
- packages/cerebral/src/operators/unshift.test.js
- packages/cerebral/src/operators/wait.test.js
- packages/cerebral/src/operators/when.test.js
Initial model state should be "no changes" or on first action run, the changes are checked and debugger may wrongly throw "you are changing 'foo' in strict mode". Problem is module initial state set.
> Fix controller init

- packages/cerebral/src/operators/set.js
- packages/cerebral/src/operators/set.test.js
- packages/docs/content/api/05_operators.en.md
Okay, I played around with different syntax. But I think we should rather explain better how "operator tags" work... cause now the syntax is very familiar and it makes sense. Keeping the `string` operator for short.
> feat(Operators): add input to set and document operator tags

- packages/cerebral/src/devtools/index.js
- packages/cerebral/src/viewFactories/Hoc.js
- packages/docs/content/getting-real/03_devtools.en.md
When refactoring we came up with the idea to show a warning if you have more than a set number of state dependencies or signals... helping out splitting up components.
> feat(Devtools): show warning on big components

- packages/tutorial/.gitignore
When `src` is part of  `gitignore` it might be hidden by IDEs, it should not do that, very confusing. The SRC folder is built up with chapter 01 when starting up anyways.
> fix(tutorial): make sure source folder is not hidden

- packages/cerebral-forms/src/factories/resetForm.js
- packages/cerebral-forms/src/factories/validateField.js
- packages/cerebral-forms/src/factories/validateForm.js
- packages/cerebral-forms/src/helpers/formToJSON.js
- packages/cerebral-forms/src/helpers/getFormFields.js
- packages/cerebral-forms/src/utils/configureField.js
- packages/cerebral-forms/src/utils/runValidation.js
- packages/cerebral-forms/src/utils/util.test.js
Move runValidation from validateField to validate.
As runValidation becomes the default export rename file to runValidation.js.
Reuse runValidation in validateForm and configureField.
> refactor(forms): merge runValidation and validate

- packages/cerebral/src/operators/set.js
- packages/cerebral/src/operators/set.test.js
Add support in "set" operator for:
```js
set(input`foo.bar`, 'baz')
```
To set **input.foo.bar**. Currently this sets `input['foo.bar']`.
> feat(Operators): support setting deep path inside "input"

- packages/cerebral-forms/README.md
Hi guys,
Form should be lowercase 
Related to cerebral/cerebral#462, you decided to keep global props outside the form. So I deleted this example and put it in factory. 
Thanks for the great library :)
> feat(forms): fixed default requiredMessage and global props factory example

- packages/function-tree/src/FunctionTree.test.js
Just a test to ensure that an edge case in Cerebral 1 does not happen in Cerebral 2
> test(function-tree): ensure inputs are passed correctly with empty paths

- packages/cerebral/src/operators/when.js
- packages/cerebral/src/operators/when.test.js
- packages/docs/content/api/07_operators.en.md
Add support for these kind of things:
```js
when(state`clients.$draft.key`, input`key`, (a, b) => a === b), {
// maybe update the form as well
}
```
> feat(Operators): add support for multiple arguments to 'when'

- packages/cerebral-debugger/electron/main.js
So stupid... the storage thing returns an object when there is no value there
> fix(debugger): fix default port on first startup

- packages/cerebral/src/viewFactories/Hoc.js
- packages/cerebral/src/viewFactories/react.test.js
if submitted properties changed do no further checking just return true so the comp gets rerendered
> fix: change priority hasChange (in submitted Props)

- packages/cerebral/src/Controller.js
The callback is sync error throwing, meaning that promises throwing an error just swallows it up again. Function tree already has async error throwing, so using that instead.
> fix(Controller): throw async errors from function tree

- packages/cerebral/src/Controller.js
- packages/cerebral/src/Controller.test.js
- packages/cerebral/src/Model.js
- packages/cerebral/src/Model.test.js
- packages/cerebral/src/devtools/index.js
- packages/cerebral/src/utils.js
- packages/docs/content/api/02_state.en.md
- packages/docs/content/in-depth/01_the-architecture.en.md
- packages/docs/content/in-depth/03_state.en.md
- packages/docs/content/in-depth/04_signals.en.md
- packages/docs/content/install/02_debugger.en.md
- packages/docs/content/tutorial/04_update-state.en.md
- packages/docs/content/tutorial/05_using-chains.en.md
- packages/docs/content/tutorial/06_using-inputoutput.en.md
Allrighty... after long and good discussions on handling binary like things (not serializable stuff) I think I found a really good solution.
We talked about identifying these on the input or use a special `.keyName` convention... but we already check the keys if they are serializable, so only thing now is to handle it differently when they are not (The payload to signal itself still has a check on being serializable though, like it needs to be a plain object):
```js
someSignal({
file: event.target.files[0]
})
```
There is so little code it is silly, the only thing it does when it is not serializable is that it attaches a `toJSON` method to the object :) 
In actual state tree it looks like:
```js
{
file: FileObject
}
```
And when serialized it looks like:
```js
{
files: …
```
> feat(Controller): add ability to handle binary like values

- packages/cerebral/src/operators/debounce.test.js
- packages/cerebral/src/operators/index.js
- packages/cerebral/src/operators/signal.js
- packages/cerebral/src/operators/signal.test.js
- packages/docs/content/api/06_operators.en.md
Usage example:
```js
firebase.upload('remote.path', state`$draft.imageFile`,
{progress: signal`clients.$draft.imageProgress`}
), {
success: [],
error: []
}
```
> feat(Operators): add signal operator to pass a signal to action/factory

- packages/cerebral/src/Controller.js
- packages/cerebral/src/Controller.test.js
- packages/cerebral/src/providers/Recorder.js
- packages/cerebral/src/providers/Recorder.test.js
- packages/cerebral/src/providers/State.js
To handle async state changes we need to run an async flush on any state change. To avoid doing unnecessary flushes the async flush will of course be reset for every new state change. There is also a general optimization here where flushes which are not forced and has no changes, does not cause a flush to happen (avoid running lots of unnecessary code).
So even though more flushes, code is faster and handles async.
You might say, why not only have async flushes? React and inputs :)
> feat(Controller): flush async state changes

- packages/forms-demo/src/components/Fields/Input/index.js
- packages/forms-demo/src/components/Menu/index.js
- packages/forms-demo/src/components/PrettyPrint/index.js
- packages/forms-demo/src/components/Simple/index.js
- packages/forms-demo/src/components/Simple/styles.js
- packages/forms-demo/src/modules/app/actions/hidePanel.js
- packages/forms-demo/src/modules/app/actions/unToggleSettings.js
- packages/forms-demo/src/modules/app/chains/toggleSelectSettings.js
- packages/forms-demo/src/modules/app/index.js
- packages/forms-demo/src/modules/simple/index.js
@edgesoft Sorry, I had no time to push it early today :( 
I created a simple task list according to your summary. 
**Simple demo**
**Checkout demo**
**Sign up demo** (confirm password)
**Fileupload demo**
**Dependent DropDown List**
> feat(demos): add onSubmit, onBlur validation and reset

- packages/cerebral-debugger/src/components/Debugger/Inspector/index.js
- packages/cerebral-debugger/src/components/Debugger/Model/index.js
- packages/cerebral-debugger/src/components/Debugger/index.js
- packages/cerebral-forms/src/rules.js
- packages/cerebral/src/Controller.js
- packages/cerebral/src/operators/debounce.test.js
- packages/cerebral/src/viewFactories/Hoc.js
- packages/cerebral/src/viewFactories/react.test.js
- packages/demo/src/components/Header/index.js
- packages/forms-demo/src/helpers/syntaxHighlight.js
- now throws error when a state path definition is undefined, typically when importing computeds wrong
- Should only warn once now for big components
- Now warns when strict render is active
- Added:
```js
connect({}, {}, (ownProps, stateProps, signalProps) => {
return {} // Overrides everything
}
```
Have not documented this yet, can do it in another pull. Got some other doc updates to do as well
> feat(Views): add props function and fix warnings

- package.json
- src/Computed.js
include the computed fn name in the output to fix nested computed cache
> fix(computed): include the computed fn name in the output

- packages/cerebral/src/viewFactories/Hoc.js
- packages/cerebral/src/viewFactories/react.test.js
Connected component often has no ownProps, so we should pass them as last argument to easy omit.
Moreover it also meets signature of react-redux connect.
> feat(Views): adjust mergeProps callback signature

- packages/function-tree/src/FunctionTree.test.js
- packages/function-tree/src/index.js
When an action contains a promise but the promise is not returned, the current error message can be confusing because all parts of the Promise may be returning a path. Maybe this message can slightly help: ...should return a path **or a Promise**
BTW, the previous test was a noop and would always pass.
> refactor(function-tree): improve error message on missing promise or path

- packages/cerebral/src/Controller.js
As it's just a regular console information, it shouldn't be treated as a warning IMHO. In my build setup, I'm getting a notification each time there are new warning messages on the node server – which is a bit annoying if it's just a regular info like in this case.
> Info about strict render should not be a warning

- packages/cerebral-provider-firebase/src/getUser.js
Firebase should not reject `onauthchange` event when there is no user. No user is considered a "success", there just is no user there. It is not the same as an HTTP request, because there are no error codes. Either it fails or it works... and "no user" works, so should be success.
> fix(firebase): always resolve onauthchange

- packages/cerebral/src/Controller.js
- packages/cerebral/src/Controller.test.js
- packages/function-tree/README.md
- packages/function-tree/src/FunctionTree.test.js
- packages/function-tree/src/executeTree.js
- packages/function-tree/src/index.js
- packages/function-tree/src/staticTree.js
Currently Cerebral triggers a flush on every `pathEnd` event from function-tree. This was added to handle situations of:
```js
[
[
asyncA, {success: [actionA], error: []}, // Need to flush as asyncB is still processing
asyncB, {success: [actionB], error: []},
]
]
```
The problem here is that there are many times `pathEnd` executes without needing to, like when paths are not related to async execution. This causes renders of app in between plain synchronous actions.
Now Cerebral is smarter. It triggers flushes on:
- Async action that is not parallel
- When parallel execution starts
- When parallel actions resolve, except the last one (handled by other events)
- When signal ends
This generally improves performance and makes Cerebral more predictable.
Fixed the bug in our app  as well, …
> feat(function-tree): parallel execution events, improve Cerebral flushing

- packages/cerebral-provider-firebase/src/createTask.js
- packages/cerebral-provider-firebase/src/createUserWithEmailAndPassword.js
- packages/cerebral-provider-firebase/src/deleteUser.js
- packages/cerebral-provider-firebase/src/factories/deleteUser.js
- packages/cerebral-provider-firebase/src/index.js
- packages/cerebral-provider-firebase/src/sendPasswordResetEmail.js
- packages/cerebral-provider-firebase/src/signInWithEmailAndPassword.js
- Can not return values from `catch` as they will be no longer propagate as errors, have to reject or throw again
- Wrapped a few methods with normal promises, cause Firebase promise is not native
> feat(firebase): delete user and throw errors correctly

- packages/cerebral-provider-firebase/README.md
- packages/cerebral-provider-firebase/src/createOnChildChanged.js
- packages/cerebral-provider-firebase/src/createOnValue.js
- Can now pass payload on other listeners as well
- `onValue` does not trigger initial value for more predictable behaviour... it is a listener for change, not grab initial value.. that is why you have `value`
> fix(firebase): pass payload also on onValue and onChildChanged

- docs/docs/content/best-practices/03_testing.en.md
- packages/cerebral/src/viewFactories/StateContainer.js
You can now add dummy signals to the test controller
```js
import { StateContainer } from 'cerebral/react'
describe('<Form />', () => {
it('handles submit button click', () => {
const testSignal = (input) => { /* assert something */ }
const wrapper = mount(
<StateContainer state={global.fixtures} signals={{ 'form.submitted': testSignal }}
<Form />
</StateContainer>
)
const button = wrapper.find('button')
button.simulate('click')
})
})
```
> feat(StateContainer): Add support for signals on the dummyController

- packages/cerebral-provider-http/README.md
- packages/cerebral-provider-http/src/factories/httpDelete.js
- packages/cerebral-provider-http/src/factories/httpGet.js
- packages/cerebral-provider-http/src/factories/httpPatch.js
- packages/cerebral-provider-http/src/factories/httpPost.js
- packages/cerebral-provider-http/src/factories/httpPut.js
- packages/cerebral-provider-http/src/http.test.js
- packages/cerebral-provider-http/src/utils.js
```js
export default [
httpPut('/items/1', { title: 'updated' }), {
'201': [],
success: [], // all other success codes will call this path
'401': [],
error: [] // all other error codes will call this path
}
]
```
> feat(http): add support for status code paths

- package.json
- packages/cerebral-forms/src/utils/validate.test.js
- packages/cerebral/src/Controller.js
- packages/cerebral/src/operators/concat.test.js
- packages/cerebral/src/operators/merge.test.js
- packages/cerebral/src/operators/pop.test.js
- packages/cerebral/src/operators/push.test.js
- packages/cerebral/src/operators/set.test.js
- packages/cerebral/src/operators/shift.test.js
- packages/cerebral/src/operators/splice.test.js
- packages/cerebral/src/operators/toggle.test.js
- packages/cerebral/src/operators/unset.test.js
- packages/cerebral/src/operators/unshift.test.js
- packages/cerebral/src/viewFactories/react.test.js
- packages/function-tree/src/index.js
Tests needed to be refactored due to how controller async throws errors to not block function tree execution and messaging debugger
> refactor(Controller): extend controller from function tree

- packages/cerebral-router/src/index.js
I realise that this may just be a temporary fix until router is updated, but it would help out a lot of have it merged until the next router stuff is ready.
> fix(router): Don't overwrite mapper option when passed to router

- .travis.yml
- babel/babel-plugin-cerebral-optimize-tags/README.md
- babel/babel-plugin-cerebral-optimize-tags/__tests__/__snapshots__/compile.js.snap
- babel/babel-plugin-cerebral-optimize-tags/__tests__/__snapshots__/run.js.snap
- babel/babel-plugin-cerebral-optimize-tags/__tests__/compile.js
- babel/babel-plugin-cerebral-optimize-tags/__tests__/run.js
- babel/babel-plugin-cerebral-optimize-tags/index.js
- babel/babel-plugin-cerebral-optimize-tags/package.json
- babel/babel-plugin-cerebral-proxy-tags/README.md
- babel/babel-plugin-cerebral-proxy-tags/__tests__/__snapshots__/compile.js.snap
- babel/babel-plugin-cerebral-proxy-tags/__tests__/__snapshots__/run.js.snap
- babel/babel-plugin-cerebral-proxy-tags/__tests__/compile.js
- babel/babel-plugin-cerebral-proxy-tags/__tests__/run.js
- babel/babel-plugin-cerebral-proxy-tags/index.js
- babel/babel-plugin-cerebral-proxy-tags/package.json
- babel/babel-preset-cerebral/README.md
- babel/babel-preset-cerebral/__tests__/__snapshots__/compile.js.snap
- babel/babel-preset-cerebral/__tests__/compile.js
- babel/babel-preset-cerebral/index.js
- babel/babel-preset-cerebral/package.json
- lerna.json
- package.json
Added a `babel-preset-cerebral` that by default included `babel-plugin-cerebral-optimize-tags` and behind the option `{proxies:true}` `babel-plugin-cerebral-proxy-tags`. 
I also added the `npm run setup:babel` that will run `setup:packages` and `babel-*`. 
There needs to be some documentation on how this can be used in the babel-loader.
> feat(babel): add initial babel plugins and preset

- packages/cerebral-provider-firebase/README.md
`input`, `state` and that like should be imported from `cerebral/tags` instead of `cerebral/operators`.
review: double-check for `toString` (I guess, it's: [packages/cerebral/src/tags/Tag.js#L102](https://github.com/cerebral/cerebral/blob/master/packages/cerebral/src/tags/Tag.js#L102))
> fix(firebase): import input,state... from tags

- docs/docs/docs/best_practices/long_running_side_effects.md
`input` should be imported from `cerebral/tags` instead of `cerebral/operators`
> fix(website): import input from tags

- packages/cerebral-forms/README.md
`input` should be imported from `cerebral/tags` instead of `cerebral/operators`
> fix(forms): import input from tags

- packages/cerebral/src/operators/set.js
- packages/cerebral/src/operators/set.test.js
- packages/cerebral/src/utils.js
Fixed issue when doing things like this:
```js
[
set(state`foo`, {}),
set(state`bar`, [])
]
```
It is the same object/array being set every time, meaning that they can get mutated in the meantime. And this only happens in production due to debugger serialization
> fix(Operators): set should make copy of object and array when used as static value

- packages/cerebral/src/Model.js
We don't need to verify values in merge method. set method has own verifyValue function
> fix(Model): don't need to verifyValue two times

- packages/cerebral/src/providers/Recorder.js
- packages/cerebral/src/providers/Recorder.test.js
Okay, so I tried implementing general events recording, but I meet problems.
1. For the debugger to replay the events it needs to manipulate the execution ID, meaning it needs to track whenever the recorder starts from scratch, so that all events get manipulated with same ID extension... it is messy
2. There is sooo much data recorded. execution data, functionDetails, payloads... it serializes, deserializes to avoid mutation... it is just so much extra overhead compared to current implementation
3. Mutations are tracked separately from function tree events and I could not get them to match up in the debugger... maybe a small mistake, but been at this for a couple of hours now and I have lost my patience ;-)
4. When seeking a recording it replays all events up to that point. This will …
> feat(Controller): add recorder events and tracking

- docs/docs/docs/developer_guide/test.md
- packages/cerebral/src/test/index.js
- packages/cerebral/src/test/index.test.js
RunSignal is still there but will show deprecation warning.
Test helper supports `getState` and `setState` as well as `runSignal`.
```js
import {CerebralTest} from 'cerebral/test'
it('should accumulate a count', () => {
const cerebral = CerebralTest({
modules: {
math: math()
}
})
cerebral.setState('math.count', 0)
return cerebral.runSignal('math.plusOne').then(({state}) => {
assert.equal(state.math.count, 1)
return cerebral.runSignal('math.plusTwo').then(() => {
assert.equal(cerebral.getState('math.count'), 3)
})
})
})
```
> Replace RunSignal test helper with CerebralTest helper

- docs/packages/forms.md
- packages/cerebral-provider-forms/src/field.test.js
- packages/cerebral-provider-forms/src/form.js
- packages/cerebral-provider-forms/src/index.js
This will allow 
```js
import {state} from 'cerebral/tags'
import {field} from 'cerebral-provider-forms'
export default connect({
myField: field(state`some.field`)
})
```
Validate will run and you will have `myField.isValid` etc
> Expose field on cerebral-provider-forms

- packages/cerebral-provider-forms/src/utils/validate.js
Currently failedRule is still set, even if it is valid. With this code change it gets set to null. As I am a JS beginner, I would appreciate, if someone else could write a test, thanks :)
> forms-provider, adjust failedRule behaviour

- debugger/connector/index.js
- debugger/electron/main.js
- debugger/src/components/Debugger/App/index.js
- debugger/src/components/Debugger/App/styles.css
- debugger/src/components/Debugger/Inspector/index.js
- debugger/src/components/Debugger/Signals/Signal/Action/index.js
- debugger/src/components/Debugger/Signals/styles.css
- debugger/src/components/Debugger/Toolbar/index.js
- debugger/src/components/Debugger/index.js
- debugger/src/modules/Debugger/index.js
- debugger/src/modules/Debugger/signals/addPortErrored.js
- demos/todomvc/src/controller.js
- Shows warning when the selected PORT is in use
- Removed auto inline state tree on signals and mutations tab. It has been confusing to people and when signals becomes rather complex you want to separate them anyways
- Now errored actions shows the props passed to them
- Long strings are now ellipsed... when editing a long string in state tree you get the full string
> feat(debugger): add several fixes

- docs/packages/function_tree.md
- packages/function-tree/src/FunctionTree.test.js
- packages/function-tree/src/index.js
Allowing to do this:
```js
new FunctionTree({
axios
})
```
It is just to simplify entry point to using it. Do not have to create providers, just pass in whatever. Helps explaining the tool as well.
Related to article:
https://gist.github.com/christianalfoni/8800f6a4bf84c0d0c7ce3e19684856e0
> feat(function-tree): allow function tree to take object as argument

- packages/function-tree/src/devtools/index.js
Current implementation having an issue with debugger events subscription. Debugger subscribes on tree events only after opening web socket connection, so the first tree events not processed (for example 'start' tree events). It prevents the debugger app to show tree execution at all.
> Fix FT debugger events subscription.

- packages/function-tree/src/devtools/index.js
No need to to anything... it is just Node that totally breaks on any error throwing. It is closing of connection that handles reconnect.
> fix(Devtools): fix error catching on function-tree devtools

- packages/cerebral/src/devtools/index.js
Same fix for Cerebral devtools as function-tree.. need to swallow errors or it will be party time in console every 5 seconds :)
> fix(Devtools): fix error handling on connection issues

- docs/api/devtools.md
- docs/get_started/debugger.md
- packages/cerebral/src/devtools/index.js
- packages/function-tree/README.md
- packages/function-tree/src/devtools/index.js
Makes function-tree devtools flexible:
```js
const devtools = new Devtools({
remoteDebugger: 'localhost:8585',
reconnect: true // Can turn off automatic reconnect
})
devtools.add(functionTreeInstance)
devtools.remove(functionTreeInstance)
devtools.destroy() // removes all instances
```
> feat(Devtools): make devtools instance based and flexible

- packages/cerebral-router/README.md
- packages/cerebral-router/src/index.js
Being able to grab certain parts of url is useful to track state changes in url. For example in Ducky app we do not care if the query has changed, but we care if the base url has changed. In @great router I suggest we add state for this:
```js
{
router: {
url: 'http://localhost:3000/items?foo=bar',
query: {foo: 'bar'},
origin: 'localhost',
port: 3000,
path: '/items'
}
}
```
Something like that... anyways, these methods are good enough for current router I think
> feat(router): add additional methods for grabbin parts of url

- docs/api/providers.md
- docs/developer_guide/providers.md
- packages/cerebral/src/Provide.js
- packages/cerebral/src/Provide.test.js
- packages/cerebral/src/index.js
Okay, so I woke up this night with an idea to a different approach making providers concept easier to understand.
So basically I have made some docs updates and added a `provide` helper. It looks like this:
```js
import {Controller, provide} from 'cerebral'
import axios from 'axios'
Controller({
providers: [
provide('http', axios)
]
})
```
The API makes it very explicit what you do, you "provide axios to Cerebral named http" . This just makes a lot more sense than some magical object in the providers array:
```js
Controller({
providers: [{
http: axios
}]
})
```
This API is flawed cause it is not explicit, what about multiple objects etc.?
There is nothing breaking about this :)
> feat(Providers): add provide factory to simplify concept of providers

- debugger/src/components/Debugger/Signals/Signal/Action/index.js
There was a bug related to iterating "data" in actions (mutations and side effects)
> fix(debugger): fix handling non data in actions

- docs/api/connect.md
I chose list to show that you can name props however you want.
> Fix typo in variable name.

- packages/cerebral/src/Model.js
- packages/cerebral/src/providers/State.js
There was only one error thrown here, making it super confusing. Now it throws these two errors:
Cerebral - The Signal "newTodoTitleChanged" with action "operator.set(state`newTodoTitle.mip`, props`title`)" has an error: The path "newTodoTitle.mip" is invalid, can not update state. Does the path "newTodoTitle" exist?
Cerebral - The Signal "newTodoTitleChanged" with action "operator.set(state`newTodoTitle`, props`title.foo`)" has an error: You are passing a non serializable value into the state tree on path "newTodoTitle"
> fix(Controller): throw correct errors related to state updates

- packages/cerebral-provider-forms/src/field.test.js
- packages/cerebral-provider-forms/src/form.js
- packages/cerebral-provider-forms/src/form.test.js
- packages/cerebral-provider-forms/src/index.test.js
- packages/cerebral-provider-forms/src/operators/resetForm.js
- packages/cerebral-provider-forms/src/operators/resetForm.test.js
- packages/cerebral-provider-forms/src/operators/setField.js
- packages/cerebral-provider-forms/src/operators/setField.test.js
- packages/cerebral-provider-forms/src/utils/runValidation.js
- packages/cerebral-provider-forms/src/utils/validate.js
- packages/cerebral-provider-forms/src/utils/validate.test.js
Hi @christianalfoni ,
- use runCompute instead of controller in form.test.js
- catch errors using new cerebral error handling 
- fix field error message, if the field is valid. It should return initialValidation without any error message.
By the way why initialValidation has failedRule key?
> test(forms): add more tests for code coverage and some changes

- packages/function-tree/package.json
- packages/function-tree/src/FunctionTree.js
- packages/function-tree/src/FunctionTree.test.js
- packages/function-tree/src/Path.js
- packages/function-tree/src/Path.test.js
- packages/function-tree/src/errors.js
- packages/function-tree/src/primitives.test.js
- packages/function-tree/src/providers/Context.js
- packages/function-tree/src/providers/Context.test.js
- packages/function-tree/src/providers/StopExecution.test.js
- packages/function-tree/src/staticTree.test.js
Hi,
again more tests :)
- fix errors. Error classes should be able to work with string or error instance.
- add primitives and path test file
- change Path.toJS method to Path.toJSON (like other classes)
- fix some typo mistakes
> test(function-tree): add more tests and some fixes

- packages/cerebral/package.json
- packages/cerebral/src/devtools/index.js
- packages/cerebral/src/devtools/index.test.js
- packages/function-tree/package.json
- packages/function-tree/src/devtools/base.js
- packages/function-tree/src/devtools/index.js
- packages/function-tree/src/devtools/index.test.js
Hi all,
PR includes:  
- create new DevtoolsBase class (get rid of code duplication)
- Cerebral Devtools and Function-tree Devtools extending from DevtoolsBase  
- new devtools tests using mock-socket
function-tree devtools
- change destroy method name to removeAll because it removes all trees but not destroy devtools
- fix remove tree should remove provider
- fix removeAll (destroy) .first copy trees then remove them safely
- fix reconnect. Before it listened onclose method two times.
cerebral devtools
- remove doReconnect from options
- fix init memory leak :) only call watchExecution if it is the first time.
- use safeStringify method for cerebral devtools.
I pushed also some fixes for debugger.  https://github.com/cerebral/cerebral-debugger/pull/3
I tested with my cerebral project. It …
> Refactor devtools

- docs/api/devtools.md
- docs/get_started/todomvc.md
- docs/introduction/debugger.md
- docs/introduction/organize.md
- docs/introduction/signals.md
- docs/introduction/state.md
- packages/demos/todomvc/src/controller.js
- packages/node_modules/cerebral/src/Model.js
- packages/node_modules/cerebral/src/devtools/index.js
- packages/node_modules/cerebral/src/devtools/index.test.js
- packages/node_modules/cerebral/src/utils.js
- packages/node_modules/cerebral/src/views/View.js
- packages/node_modules/cerebral/src/views/react/react.test.js
- packages/node_modules/function-tree/src/devtools/base.js
- packages/node_modules/function-tree/src/devtools/index.js
- packages/node_modules/function-tree/src/devtools/index.test.js
- Now using `host` instead of `remoteDebugger`... it has been DEPRECATED
- The `View` will now verify the props passed into it. It checks if any of the props are complex objects and if they are frozen. If this is the case it is coming from the Cerebral state tree and should not be there, it should be connected directly. It gives a warning when this occurs
- Fixed issue where root state update was not frozen
- Fixed issue where devtools would replace state and not freeze on `remember` and `reset`
- Updated docs to reflect new `host` prop
> feat(Devtools): change to host prop and warn use of frozen objects in props

- packages/demos/forms-demo/src/index.js
- packages/node_modules/@cerebral/forms/README.md
- packages/node_modules/@cerebral/forms/src/field.test.js
- packages/node_modules/@cerebral/forms/src/form.js
- packages/node_modules/@cerebral/forms/src/index.test.js
- packages/node_modules/@cerebral/forms/src/rules.js
- packages/node_modules/@cerebral/forms/src/rules.test.js
- packages/node_modules/@cerebral/forms/src/util.test.js
- packages/node_modules/@cerebral/forms/src/utils/checkHasValue.js
- packages/node_modules/@cerebral/forms/src/utils/runValidation.js
- packages/node_modules/@cerebral/forms/src/utils/validate.js
- packages/node_modules/@cerebral/forms/src/utils/validate.test.js
This change is breaking IF you have created custom rules using the second/third argument. Now the args to rules are: `value`, `arg` and `get`. The `get` is from the computed allowing a rule to depend on any state or props passed to component, also tracking changes to it for rerender. This fixes issues where one field depends on an other etc.
> feat(forms): use get from computed instead of form in rules

- packages/node_modules/@cerebral/http/src/DEFAULT_OPTIONS.js
The error occurs when there are no headers in the server response settings. We get "Uncaught TypeError: Can not read property" indexOf "undefined"
> fix(http): fix error indexOf of undefined, if there are no headers

- docs/api/components.md
- packages/node_modules/cerebral/src/views/angularjs/module.js
Having direct access to cerebral's controller is crucial for many use cases within Angular. This PR exposes it as a `controller` property on the `cerebral` service.
Also updated docs with an example.
> feat(Views): Expose cerebral controller in Angular.js service

- packages/node_modules/cerebral/src/UniversalController.js
- packages/node_modules/cerebral/src/UniversalController.test.js
Add an option to skip runOnce check in UniversalController.
> feat(UniversalController): allow multiple runs of Signals.

- packages/node_modules/function-tree/src/FunctionTree.js
Fixes https://github.com/cerebral/cerebral/issues/984
> fix(function-tree): errors should not be rethrown in promise catch

- packages/node_modules/cerebral/src/views/View.js
- packages/node_modules/cerebral/src/views/angularjs/module.js
Added a new feature to the `View` factory. Now you can choose to drag out all props, or just state props. This is necessary for view solutions where props are not being passed down, like in angularjs.
> fix(Views): fix angularjs ctrl prop override bug

- .travis.yml
Travis only expands secure envs for commits directly from cerebral/cerebral. Check if they exist
before using them so that PRs from forks can be tested.
> chore(travis): check for travis secure envs

- package.json
- scripts/release/master.js
- scripts/release/next.js
Okay, now we run releases with:
`npm run release:master`
`npm run release:next`
To actually run release, add `-- --publish` after the command
> chore(release): add next release script and remove forced major

- .travis.yml
This works on the repo-cooker-test and should let us start the auto-publish freedom and fame !
> chore(monorepo): fix how travis creates npm login

- package.json
- packages/node_modules/cerebral-mobx/.babelrc
- packages/node_modules/cerebral-mobx/README.md
- packages/node_modules/cerebral-mobx/index.js
- packages/node_modules/cerebral-mobx/package.json
- packages/node_modules/cerebral-mobx/src/Model.js
- packages/node_modules/cerebral-mobx/src/StateProvider.js
- packages/node_modules/cerebral-mobx/src/index.js
- packages/node_modules/cerebral-mobx/src/index.test.js
- packages/node_modules/cerebral/src/BaseController.js
- packages/node_modules/cerebral/src/Model.js
- packages/node_modules/cerebral/src/Model.test.js
- packages/node_modules/cerebral/src/Module.js
- packages/node_modules/cerebral/src/index.js
- packages/node_modules/cerebral/src/utils.js
- `BaseController` handles modules, signals and providers
- `Controller` is now only related to default Cerebral model, dependency tracking and flushing
- Moved `StateProvider` as property to the Model itself, so each model can have its own state provider
- Added `cerebral-mobx` package, which just exports the Mobx (Mobx State Tree) controller and handles `model` property in modules
Check README.md on how it works in practice. 
This is of course rather experimental and should be tested more before any new release. But I really want to explore this as it simplifies Cerebral code and at the same time "empowers" the model layer with typing etc. It does of course not support a bunch of view layers, like default Cerebral model, so this could be just a choice for the developer.
> feat(Controller): refactor to base controller and add mobx state tree

- packages/node_modules/@cerebral/forms/src/helpers/resetForm.js
- packages/node_modules/@cerebral/forms/src/helpers/resetForm.test.js
having a falsy defaultValue in a form field, would reset the field to an empty string.
changed this behavior, to allow falsy defaultValues and added a test case.
> fix(forms): allow falsy values as defaultValue

- package.json
This will allow us to not change Cerebral sources if we need to fix repo-cooker.
> chore(monorepo): use the latest repo-cooker for now

- packages/node_modules/@cerebral/baobab/package.json
- packages/node_modules/@cerebral/forms/package.json
- packages/node_modules/@cerebral/http/package.json
- packages/node_modules/@cerebral/inferno/package.json
- packages/node_modules/@cerebral/mobx-state-tree/package.json
- packages/node_modules/@cerebral/preact/package.json
- packages/node_modules/@cerebral/react/package.json
- packages/node_modules/@cerebral/router/package.json
- packages/node_modules/@cerebral/shortcuts/package.json
- packages/node_modules/@cerebral/storage/package.json
- packages/node_modules/@cerebral/useragent/package.json
- packages/node_modules/cerebral/package.json
- scripts/release/index.js
We do not want to have circular depencencies because this prevents release with repo-cooker.
> chore(release): change dependency on cerebral from normal to peer

- packages/node_modules/cerebral/src/views/View.js
- packages/node_modules/cerebral/src/views/View.test.js
- packages/website/builder/pages/index/index.js
- scripts/release/index.js
The new repo-cooker now supports circular dependencies (Yeah !) so we should not filter out dependencies because this leads to invalid "@next" releases (peer dependency mess or worse multiple cerebral versions installed and breaking apps).
Made the log 25vh instead of 50vh because it is really too big now and pushes the important links way down....
Please let me pull this PR in when it is approved (need to bust cache for repo-cooker).
> Fix release with new repo-cooker, fixes view error message, change logo size

- packages/node_modules/cerebral/test.d.ts
- packages/node_modules/cerebral/test/typescript/test.ts
We now support up to 3 typed actions in `runSignal` tester.
> fix(types): runSignal types were wrong.

- docs/introduction/test.md
Added a comment: Users otherwise may not notice that a module they include in a fixture overrides the state they are explicitly declaring on the fixture.
> Comment: Module state overrides fixture state

- docs/api/controller.md
- docs/api/universalcontroller.md
- packages/node_modules/cerebral/src/BaseController.js
- packages/node_modules/cerebral/src/UniversalController.js
- packages/node_modules/cerebral/src/UniversalController.test.js
This is basically how it looks in `next.js`:
```js
import React from 'react'
import {Controller, UniversalController} from 'cerebral'
import Devtools from 'cerebral/devtools'
import {Container} from '@cerebral/react'
import modules from '../modules'
import Page from '../components/Page'
export default class extends React.Component {
static async getInitialProps({pathname}) {
const controller = UniversalController({modules})
return controller.runSequence([
function setPage ({state}) {
state.set('app.currentPage', 'home')
}
])
.then(() => {
return {
stateChanges: controller.getChanges()
}
})
}
render() {
return (
<Container controller={Controller({
devtools: typeof window === 'undefined' ? null : Devtools({host: 'localhost:8787'}),
stateChanges: this.props.stateChanges,
modules
})}>
<Page …
```
> Next.js support

- docs/api/providers.md
- docs/introduction/providers.md
- packages/node_modules/cerebral/src/Provide.js
- packages/node_modules/cerebral/src/Provide.test.js
This heavily simplifies creating providers.
```js
provide('foo', {})
```
Is current API, but now added
```js
provide('foo', (context) => ({}))
```
Basically the low level version is no longer needed, only for internal crazy stuff. So have highlighted these two simple approaches and explicitly stated the manual one as "low level". All packages can really start using the `provide` with a function now. Caching and debugger wrapping for free :)
Thanks @Guria for inspiration!
> add context callback version of provide API

- scripts/release/releaseNotesTemplate.js
Looks like this: https://gist.github.com/christianalfoni/1c0746c3d67393e1463a2df9c0a4ae24 (note the commit hashes are a lot shorter in actual release notes) :)
> chore(release): add breaking list to breaking table

- packages/node_modules/@cerebral/storage/src/StorageProvider.js
When setting a value to undefined it gets serialised to 'undefined' string, then when parsing the storage value back to json later it fails since 'undefined' is truthy.
Instead it should not be possible to set undefined, setting undefined now removes the key.
This also fixes sync with unset state values.
> fix(storage): Setting key value to undefined should unset key

- packages/node_modules/function-tree/src/staticTree.js
> fix(function-tree): use indexOf instead of startsWith available only in ES6

- packages/node_modules/@cerebral/router/README.md
- packages/node_modules/@cerebral/router/src/base.js
- packages/node_modules/@cerebral/router/src/router.js
Adds the option to add new routes after the router module has been initialised. Useful for lazy loading app parts and for app security.
Not tested, just a concept!!!
> Include addRoutes method on router module

- packages/node_modules/@cerebral/http/README.md
- packages/node_modules/@cerebral/http/index.d.ts
- packages/node_modules/@cerebral/http/operators.d.ts
- packages/node_modules/@cerebral/http/src/operators/httpDelete.js
- packages/node_modules/@cerebral/http/src/operators/httpGet.js
- packages/node_modules/@cerebral/http/src/operators/httpPatch.js
- packages/node_modules/@cerebral/http/src/operators/httpPost.js
- packages/node_modules/@cerebral/http/src/operators/httpPut.js
`@cerebral/http` operators now accept and pass through options.
> feat(http): pass through options from operators

- docs/api/tags.md
- packages/node_modules/cerebral/src/BaseController.js
- packages/node_modules/cerebral/src/Controller.test.js
- packages/node_modules/cerebral/src/View.js
- packages/node_modules/cerebral/src/View.test.js
- packages/node_modules/cerebral/src/tags/index.js
- packages/node_modules/cerebral/tags/index.d.ts
Hello! I thought it was a good idea to allow all module signals to be pushed right into the view without needing to specify each signal separately.
Example of usage:
```
@connect({
moduleSignals: signals`someModule`
})
...
props.moduleSignals.moduleSignal(payload)
```
What do you think about it?
This PR is the recreation of https://github.com/cerebral/cerebral/pull/1155
> Add 'signals' tag to target all the signals of the specified module

- packages/node_modules/@cerebral/inferno/index.d.ts
> ts(inferno): use InfernoChildren type instead of undefined JSX type

- packages/node_modules/@cerebral/inferno/src/Hoc.js
Registering inferno components within componentDidMount triggers a "TypeError: Cannot read property 'dom' of null" on server side.
According to https://daveceddia.com/where-fetch-data-componentwillmount-vs-componentdidmount/ it might be better to use componentDidMount instead of componentWillMount. Tested without issue on local project.
Review and discussion welcome.
Probably related to this issue: https://github.com/infernojs/inferno/issues/1215
> Change inferno render hook to avoid TypeError on SSR

- packages/node_modules/@cerebral/mobx-state-tree/README.md
TypeScript complains if the order of these decorators is different.
```index.module.js:858 Mobx observer: You are trying to use 'observer' on a component that already has 'inject'. Please apply 'observer' before applying 'inject```
> @observer has to be after @inject

- packages/node_modules/@cerebral/forms/src/rules.js
maxLength checks on null or undefined lead to an exception. Note that contrary to minLength, we don't need to check isEmpty since the length is defined for an empty string and its length 0 works fine with maxLength.
> maxLength: check isExisty before checking length

- packages/node_modules/cerebral/index.d.ts
- packages/node_modules/cerebral/src/Module.test.js
- packages/node_modules/cerebral/src/index.js
This is needed to detect if an exported module is a Module or not.
In 'blocks', I use functions to define signals and therefore need to pass module definitions to 'boot' without wrapping them. Wrap with Module should only be done if it hasn't been done yet (like with router), hence the instanceof thing.
As a general question, I am wondering why we expose `Module` publicly at all. It would make the API much simpler without it, letting the controller do the wrapping.
> fix(Module): expose ModuleClass so that we can test for instanceof.

- packages/node_modules/@cerebral/firebase/README.md
- packages/node_modules/@cerebral/firebase/operators.d.ts
- packages/node_modules/@cerebral/firebase/src/getDownloadURL.js
- packages/node_modules/@cerebral/firebase/src/index.js
- packages/node_modules/@cerebral/firebase/src/operators/getDownloadURL.js
- packages/node_modules/@cerebral/firebase/src/operators/index.js
Adds getDownloadURL to the firebase provider. This allows for generating file-urls based on path and filename. Typically used for generating image-urls to put in img-tags based on filename and path in firebase storage.
> feat(firebase): add getDownloadURL to firebase provider for storage

- packages/node_modules/@cerebral/router/README.md
- packages/node_modules/@cerebral/router/index.d.ts
- packages/node_modules/@cerebral/router/src/router.js
- packages/node_modules/@cerebral/router/src/router.urlMapping.test.js
- packages/node_modules/@cerebral/router/test/helper.js
Fix the problem reported at https://github.com/cerebral/cerebral/issues/1244. The original code always set the default state value to null.
> fix(router): preserve the default state value

- packages/node_modules/@cerebral/router/src/router.js
- packages/node_modules/@cerebral/router/src/router.urlMapping.test.js
- packages/node_modules/@cerebral/router/test/helper.js
Fix the problem reported at #1244. The original code always set the default state value to null.
Moved from #1245 and cleaned up.
> fix(router): preserving the default state value

- packages/node_modules/cerebral/index.d.ts
- packages/node_modules/cerebral/test/typescript/definitions.test.js
- packages/node_modules/cerebral/test/typescript/helper.js
- packages/node_modules/cerebral/test/typescript/index.test.ts
Related issue #1167 
For `runSequence()`, I was looking through how `function-tree` is typed, and find out it is using:
```
createStaticTree(tree: Primitive | Array<Function | Primitive>): Array<Primitive>
```
I wonder for `controller` usage, we might want more specific `SequenceFunction<TStateAndProps>() => any` than `Function` since I see that's used for in example:
```
controller.runSequence([
function myAction ({ state, props }) {
state.set('app.isAwesome', props.isAwesome)
}
], {
isAwesome: true
})
.then(() => {
// I am done running
})
```
> Add missing UniversalController typing

- packages/node_modules/@cerebral/forms/index.d.ts
getting `'FormsProvider', which lacks return-type annotation, implicitly has an 'any' return type` error, had to add the return type as *Provider*
> ts(forms): add Provider return type

- packages/node_modules/@cerebral/http/src/DEFAULT_OPTIONS.js
When transferring files over forms with a content-type header of "multipart/form-data", the browser
needs to be able to additionally set a boundary value. This is only possible if the content-type
header is not explicitly set. With this commit, one is able to set the content-type header to
"undefined" which forces the browser to use "multipart/form-data" with its own boundary value for
the transferred files.
> feat(http): content-type header can be set by browser

- packages/node_modules/@cerebral/router/src/router.js
- packages/node_modules/@cerebral/router/src/router.urlMapping.test.js
fixed implementation #1253.
with the previous solution, it was not possible to change the mapped state via url, if the state was already set. see tests for an example.
> fix(router): change mapped state on url change

- package.json
- packages/node_modules/@cerebral/http/README.md
- packages/node_modules/@cerebral/http/index.d.ts
- packages/node_modules/@cerebral/http/package.json
- packages/node_modules/@cerebral/http/src/DEFAULT_OPTIONS.js
- packages/node_modules/@cerebral/http/src/HttpProviderError.d.ts
- packages/node_modules/@cerebral/http/src/HttpProviderError.js
- packages/node_modules/@cerebral/http/src/HttpProviderError.test.js
- packages/node_modules/@cerebral/http/src/http.test.js
- packages/node_modules/@cerebral/http/src/request.js
- packages/node_modules/@cerebral/http/src/utils.js
Added `timeout` option
Added `ontimeout` callback to throw as an error
Upgraded xhr-mock to be able to add tests for timeout
TODO: 
ISSUES CLOSED: #774
> feat(http): add support for timeout

- packages/node_modules/@cerebral/angularjs/README.md
- packages/node_modules/@cerebral/angularjs/src/module.js
Updates the AngularJS view to work with Cerebral 4.x.
Services are not wrapped with Provider due to many AngularJS services having properties, preventing them from working with Provider.
Also fixes an important bug where props that were not part of update in current cycle, would be removed from controller.
> Update AngularJS view

- packages/node_modules/@cerebral/http/src/request.js
Turns out setting properties on the `xhr` like `timeout` prior to calling `open` raises an `InvalidStateError` in IE11. Calling open prior to setting all of the properties resolves this exception. 
I tested the change in IE11, Chrome, Firefox and MS Edge to ensure it has no unintended side effects.
> fix(http): open xhr request prior to setting properties to fix IE11 InvalidStateError

- packages/node_modules/babel-plugin-cerebral/__tests__/__snapshots__/compile.js.snap
- packages/node_modules/babel-plugin-cerebral/__tests__/compile.js
- packages/node_modules/babel-plugin-cerebral/index.js
Just as request on discord. The babel plugin now supports namespaced imports like this:
```js
import * as proxies from 'cerebral/proxy' 
proxies.state.foo.bar
```
will be transformed to 
```js
import * as proxies from 'cerebral/tags' 
proxies.state`foo.bar`
```
> Add proxy namespace support

- packages/node_modules/babel-plugin-cerebral/__tests__/__snapshots__/compile.js.snap
- packages/node_modules/babel-plugin-cerebral/__tests__/compile.js
- packages/node_modules/babel-plugin-cerebral/index.js
Like asked on discord. This PR allows for using proxied tags like this:
```js
import * as proxies from 'cerebral/proxy';
const bar = proxies.state;
bar.hello.world;
```
↓↓↓↓↓
```js
import * as proxies from 'cerebral/tags';
const bar = proxies.state;
bar`hello.world`;"
```
Regarding the problem in todomvc-ts. I changed the import to `import * as tags from 'cerebral/proxy'` but I am still getting a typescript error:
```
Property 'sequences' does not exist on type 'typeof "/Users/FWeinb/GitHub/cerebral/packages/node_modules/cerebral/proxy/index"'.
```
Which sounds like a error outside of the babel-plugin. For typescript one should import 'cerebral.proxy' anyway, right?
> Allow assigning proxied tags to variables

- packages/node_modules/cerebral/src/index.js
- packages/node_modules/cerebral/src/test/index.js
* Docs and types mention sequence and parallel exports from 'cerebral' but they were not exported.
```js
// Now this works
import { sequence } from 'cerebral'
import * as actions from '../actions'
export const mySequence = sequence([actions.someAction])
```
* Improved test failure on missing sequence
> Fix export

- packages/node_modules/cerebral/src/factories/when.js
- packages/node_modules/cerebral/src/factories/when.test.js
If we have a compute on the path, it does not resolve the compute value and always returns `true` (the compute object).
```js
when(state.some.compute) // <=== should get compute value, not return true every time
```
> fix(cerebral): fix when tag to work with Compute in state tree

- docs/api/app.md
- packages/node_modules/cerebral/index.d.ts
- packages/node_modules/cerebral/src/BaseController.js
- packages/node_modules/cerebral/src/test/index.js
- packages/node_modules/cerebral/test/index.d.ts
The `noRethrow` controller option prevents throwing errors. This is used if the
user has an `on('error')` handler and does not want double errors.
The `CerebralTest` thing now has this option set `on` by default. Without this option, errors thrown in promises pop up later when a setTimeout is encountered which is very disturbing (looks like a Heisenbug).
Since snapshot testing does not handle errors, we don't need the option to be changed there.
This PR also contains some fixes to TS types used in testing and some missing options for controller.
> fix(test): prevent double throwing of errors in tests with new option

- packages/node_modules/@cerebral/react/index.d.ts
- packages/node_modules/cerebral/index.d.ts
- packages/node_modules/cerebral/package.json
- packages/node_modules/cerebral/src/View.js
- packages/node_modules/cerebral/src/View.test.js
Inside views we can now do:
```js
connect(
{},
function SomeView({ get, tagProp }) {
const path = get.path(tagProp)
const value = get(tagProp)
}
)
```
Real practical example. In this example, the `input` name is extracted with `get.path` on the state
prop (which also serves to get value).
```html
<Field state={state.login.username} icon />
```
> feat(cerebral): add path getter on 'get' with 'get.path' in views

- packages/node_modules/cerebral/index.d.ts
- packages/node_modules/cerebral/src/BaseController.js
Fixed `addModule` to receive both ModuleClass and ModuleDefinition so that users can adapt to deprecation warning.
Fixed other types.
> No public api should depend on Module

- packages/node_modules/@cerebral/angular/src/CerebralComponent.ts
when feeding child component props and the props changes the ngOnChanges binding code does not run with out this, if child have compute the compute value get stale in the child component
> fix(angular): missing ngOnChanges

- docs/api/factories.md
- packages/node_modules/cerebral/src/factories/set.js
- packages/node_modules/cerebral/src/factories/set.test.js
I've been using a custom version of the `set` operator/factory for the last couple of years with support for a transformFn, so it seems that it might be of use to others too.
```js
set(state.some.number, props.number, (value) => value * 2)
```
> feat(cerebral): Add support for transform functions on set factory

- docs/introduction/sequences.md
As I was reading the [introduction/sequences](https://cerebraljs.com/docs/introduction/sequences.html) documentation, I found what appears to be a typo.
Next page [Organize](https://cerebraljs.com/docs/introduction/organize.html) uses `isLoadingPosts` without `t` in the state name between `is` & `LoadingPosts`.
I've changed `istLoadingPosts` state to `isLoadingPosts` to be consistent with other state name, `isLoadingUser`.
> Fixed typo - from istLoadingPosts to isLoadingPosts

- packages/node_modules/cerebral/src/View.js
@christianalfoni while browsing the code for `mergeProps` i noticed that getters are probably unnecessarily recreated (if i'm wrong please discard this PR).
Another thing that made me wonder: if i define `mergeProps` fn, then `getProps` return early without attaching `get` and `reaction` to props. Wouldn't it be more consistent if these were always available?
> refactor(view): don’t recreate getters

- docs/introduction/tutorial.md
The link currently goes to `https://cerebraljs.com/docs/advanced/the_architecture` which is a 404.
I've changed it to direct to `docs/introduction/the_architecture` and `/docs/advanced/index`
> Fix broken link in tutorial.md

- docs/introduction/tutorial.md
There was a `]` missing, and I removed an `an` too many.
> docs(website): Fix markdown link to introduction
